[package]
name = "pettyscript"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-kinds = "0.5.1"
logos = "0.15.0"
miette = { version = "7.4.0", features = ["fancy"] }
thiserror = "2.0.11"
ustr = "1.1.0"
